; Habilita la subida de archivos mediante el protocolo HTTP
file_uploads = On

; Define la cantidad máxima de memoria (en megabytes) que un script de PHP puede consumir
memory_limit = 128M

; Establece el tamaño máximo permitido para un solo archivo subido en una petición
upload_max_filesize = 32M

; Define el tamaño máximo de datos permitidos para peticiones enviadas por el método POST
post_max_size = 32M

; Especifica el tiempo máximo (en segundos) que se le permite ejecutar a un script antes de que el servidor lo termine
max_execution_time = 300

; Especifica el tiempo máximo (en segundos) que PHP dedica a recibir datos de entrada
max_input_time = 300